services:
  - type: web
    name: student-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --workers 4 --timeout 200
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
